sudo: required
language: java
jdk: oraclejdk8
dist: trusty
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: 0jag4OR/y4VoQxae98vlpAd8htHG5IKeMosX5IY/qQx8BIyJ2rXoUyVXbRL6HKjjB1ntdIp/2chiqGCgoOtZwSk2EUjublt6WThP+UV9LYja4N/hbSqGkOd/QWqRUHmU3XyyEgiwudoM6l1G5i0RCUSbvXFt6Cdi/8iuPTRMDF/DInp7YHDuw5vxeHt8GLtdk+rL5hmjJqKUKzd9Iv9ANU9CGYEY17fhQtldDae3extggmMh/fUBDvmYkwjze5DHfqh7mF6FvtAeh+tVqnbbYuPFTKOTjglxVj8ickt3L6fYpV+Im5rJVA5NIgy9BVgfxCdQSwBeKKmfW5K0Z0ytzSgWb56ovh3a1MuBb4B+vnqrrqH/YxodRrJybyT9H9C00++b3jQIivKXgTHKSQ5YxzRr2GAouzALELtljqnS4L2pHH8M/8GiB+z82z4HGDTW7KEJfxQHW+k/s2+x42y1ZBlGFT8L5PK0UjjLluIW4Y41nEbl5ycvQpiY3q7X0JENbErop0dfKg8SEDd1aoP0o3aK1s2mDVpFO5C88V0yp46ipE02VUDLujeMZd/p7F9ZJg+UsYRbh/6d8NJ9wVb9cckeIPzdQ3SMUpG1XnX0Tka4a0h0OT1shOTpd/j5V63sJ+w3LWBHmjBdkiwc0uLXVu4q6lyhubVSTKYZFVSYG1A=
  - secure: QgKy3eN3hpC0wynr69LCUtuXxH/KT31e6EJzFouNZCScscpfJBrhla1YBtdun8nH9tGb8pcgslcoGF6j2EtA1ooTWzira9egAJeD75fs4tPeUXgo8yuvBxEhLtvt6fellte5hd3FU0zD6gpSUYAlmg8K6ZQy5I3ZxdRp5UcofYN6gcrp8mK18070mP17U/+Q8j6ezgDXttk6poW/QBGGVXCGg2NWAxUZjlLNmTtAzTLViqrg+SG9TPUUbAZ5kkFO1JXcFECbsP0G2RIjymuZQpIWZ/n6OPPxuSiVP4bw/MJBWoIDUdvGOlEwXxb0OiAiuue9zOZwVQZN3kqeRa7Mx9I9WRr5Zc7kxw2lFsovCCIOsd+43NpOuEiIuO1nBiOxFjebw8RTWcOJLa4wMokmpIImvX63gcwcTe/BojUrIIlYldYKYM3Wt7loJbQ70hZh/Ib3jNqcJNph3YPxXF5Z3EK8RnPu8J2VTvMCw8btczcsU7SzTZsW0QgUwhQ9/kFt4ot/+rXvAogcQ6cFuQCSlHq6BH9wVsZTo81MxchQRLUPPdWlF2ySPz3E2+Ol+8XEp2eBFApji+RFtOK9XZ/pKMVv733q9VChNkd9Qdu7HO/k7SJQLLso+KcbTdADT7kQ7/x7GZ0fOR2rCPevb4GHztXwOvE25yr+bCkZTVcrNkM=
  - secure: niHNSLBTUtjz8gdu0S7BJ0ZHSQdqIXkr95bcumVj/cwTRLhm7dcg5XXt0DvasJYJsR38RLn//jgLRJwQqSkIoMmt8J3/FkmYkzyMKQoBZIFyPlnw2tJr4GcihW8jWoGHFNRHV0+nYs1E4fQY4SybffzfLvohZ0lGZOo9ItA9ueZL1AI7yyuolELx9JftD3k1YvHTqC7x7sTaggisdjI9Ag+SxBQd1XSEkgojekJilD1YiGPM2sjliz4dkJ+wcgzKWt3zM9e1F3hRK1InJSvZVlbiln+ng0g4KmS5wG3u38HV8NkAlZWwEFl/mi9Rvc+HudEhir3QQirEkyCawTuqZWCdMHPCIL+lPelV6P2CLO2EqimNyxXvhuTvM+ka3r5uMPRamQ3xdTN+ruWuHI9QDhdTn8RBkLsnAAVU9F1OZFO2AnYp5PsNXfLKCrBXhs+y8xgsFNOvMFB7jhHIjutrwVMnY5l8WNfbWRU9kGIi+qVMl9bw1XS4zIRZa1upATvZL78PNH3MqM2fhtdQjD24uR2cp2SHNO3mmfy4oAt6lgl0yVIQwwuvneLjeAb/dg4cWZ9HCdV3C1LF3zi9Blp/UNP/pjbYSb7qmrNIA6ZBv1kp2XhPWtXs/hemG88qPefyUIaKgAK/fkcAeUn8qwqV7sHflhuFwhVKh+er0/I2pPU=
addons:
  sonarcloud:
    organization: hydroblok
    token:
      secure: "$SONAR_TOKEN"
script:
- "./mvnw clean install -B"
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=hydroblok/car-rental-demo
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
